### ISSUE TITLE
souci avec le changement d'heure

### ISSUE THREAD

**Issue by malooxrp** [Kla-w/celcaca-to-ical#3]
Salut !
je ne sais pas si ça a déjà été signalé, mais il y a un petit souci avec le passage à l'heure d'hiver : tous les cours sont décalés une heure plus tôt ! on peut bidouiller le problème en modifiant le fuseau horaire de l'agenda, mais c'est un petit peu crado (et ça décale aussi tous les autres évènements du coup !)
si il y a moyen de corriger ça, ça serait super cool, merci pour le boulot déjà fait !

**Comment by hugo-clemente** [comment]
Yop !
J'ai réglé le problème, j'en ai profité pour virer les "null" qui apparaissaient dans le lieu des events.
Merci d'avoir signalé le bug 😉
