### ISSUE TITLE
Aucun évènement après le 30/09

### ISSUE THREAD

**Issue by malooxrp** [Kla-w/celcaca-to-ical#4]
Bonjour,

est-il normal qu'aucun cours ne soit retranscrit dans le .ics après le 30/09 ?
Est-ce qu'il faut juste patienter quelques temps le temps que l'outil se mette à jour sur celcat ?

Merci, et bonne journée !

**Comment by ElDonad** [comment]
Salut ! 
En fait l'auteur doit mettre à jour l'intervalle de récupération des évènements. J'ai envoyé un Pull Request correctif il y a quelques jours, mais je n'ai pas reçu de réponses depuis. Vu qu'il y a d'autres personnes intéressées, je vais possiblement mettre en ligne une version fonctionnelle de l'app...

**Comment by hugo-clemente** [comment]
Je viens de voir l'issue désolé 😅. On a qu'à en discuté sur la PR, j'vais essayer de résoudre rapidement le problème
